### ISSUE TITLE
Investigate indexing issues

### ISSUE THREAD

**Issue by monicapatel21** [wri/wri_sites#243] opened 2023-12-18 22:07 UTC
The index is showing 100% on [wri.org](http://wri.org/), but the the editorial team flagged that not all Insights articles are getting pulled into https://www.wri.org/resources/type/insights-50 (for example this one from Dec 8: https://www.wri.org/insights/oil-natural-gas-emissions-us). Any idea what the issue might be?

**Comment by mariacha** [comment] 2024-01-02 22:24
I was seeing some odd behavior for this as well -- the node changes, but the issue is the same. Here's how I'm testing it:

This is a view built with solr:
https://www.wri.org/resources/type/insights-50

And this is a view built with a database query:
https://www.wri.org/admin/tmp-insights

<img width="1627" alt="Screenshot 2024-01-02 at 2 11 42 PM" src="https://github.com/wri/wri_sites/assets/999525/d1bd7412-6788-49bc-8c4a-8ab6abeaeab0">

Two high-up articles - [Outside the Spotlight, Forests and Nature Saw Important Wins at COP28](https://www.wri.org/insights/cop28-outcomes-forests-nature) and
[Under New Guidance, “Sustainable” Aviation Fuel in the US Could Be Anything But](https://www.wri.org/insights/us-sustainable-aviation-fuel-emissions-impacts) didn't show up for the solr search, but did for the database search.

Re-indexing fixed it, but I don't suspect it's fixed forever. I'll check back on it.

**Comment by mariacha** [comment] 2024-01-03 15:08
Still looks good this morning, but I'll also review after new content is posted tomorrow to see if that changes anything.

**Comment by mariacha** [comment] 2024-01-04 17:51
Update - I checked back today and there were 2 missing items -- the top one, and [3 Cutting-Edge Satellite Technologies Showcase Nature’s Impact on Water](https://www.wri.org/insights/satellites-nature-based-solutions-water-monitoring). Re-saving the top item made both show up. Total results were 2591 afterwards (I didn't note what it was before). 

So there must be something about adding a new node to the list that's altering it. I can see if I can reproduce that on a multidev.

**Comment by mariacha** [comment] 2024-03-26 16:14
This is tied to https://github.com/wri/wriflagship/issues/1160 and so can be closed as a duplicate.

**Closed by mariacha** 2024-03-26 16:14 UTC
Labels: status
